### ISSUE TITLE
Possibility to arrange value around the prefix

### ISSUE THREAD

**Issue by Jeredian** [MolchanovDmitry/CommitPrefixIdeaPlugin#1]
It can be cool if it will possible to add additional text around the result regex value, f.e. "[" "]", or ":".

```
feature/JIRA-TASK-123/sub-task => [JIRA-TASK-123]
feature/JIRA-TASK-123/sub-task => JIRA-TASK-123:
```

And the second thing is about the possibility to add an option to convert regex value to the UpperCase, or LowerCase.

```
feature/jira-task-123/sub-task => JIRA-TASK-123
feature/JIRA-TASK-123/sub-task => jira-task-123
```

@MolchanovDmitry, what do you think about it?

**Comment by MolchanovDmitry** [comment]
Please, take a look: https://github.com/MolchanovDmitry/CommitPrefixIdeaPlugin/releases/tag/4.0

**Comment by MolchanovDmitry** [comment]
@Jeredian

**Comment by Jeredian** [comment]
@MolchanovDmitry looks awesome. Thanks for so fast implementation and your support.

**Comment by Jeredian** [comment]
@MolchanovDmitry, any updates for the https://plugins.jetbrains.com/plugin/16109-commitprefix ?

**Comment by MolchanovDmitry** [comment]
@Jeredian , thank you for reminding. I'll do it on this weekend.

**Comment by MolchanovDmitry** [comment]
@Jeredian, done.
